In [1]:
import tensorflow as tf

In [9]:
x_data = [[1, 2],
          [2, 3],
          [3, 1],
          [4, 3],
          [5, 3],
          [6, 2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]

X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))


In [10]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)
            
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: \n", h, "\nCorrect (Y): \n", c, "\nAccuracy: \n", a)
    

0 0.552118
200 0.408145
400 0.393854
600 0.380665
800 0.368327
1000 0.356699
1200 0.345693
1400 0.335252
1600 0.325332
1800 0.315897
2000 0.306918
2200 0.298367
2400 0.290221
2600 0.282455
2800 0.275048
3000 0.26798
3200 0.261232
3400 0.254786
3600 0.248623
3800 0.24273
4000 0.23709
4200 0.231689
4400 0.226514
4600 0.221552
4800 0.216792
5000 0.212223
5200 0.207835
5400 0.203618
5600 0.199562
5800 0.19566
6000 0.191903
6200 0.188284
6400 0.184796
6600 0.181432
6800 0.178186
7000 0.175053
7200 0.172027
7400 0.169102
7600 0.166275
7800 0.163539
8000 0.160892
8200 0.15833
8400 0.155847
8600 0.153441
8800 0.151108
9000 0.148845
9200 0.14665
9400 0.144518
9600 0.142448
9800 0.140438
10000 0.138483

Hypothesis: 
 [[ 0.02624733]
 [ 0.15227036]
 [ 0.28259054]
 [ 0.79175204]
 [ 0.94592196]
 [ 0.98231965]] 
Correct (Y): 
 [[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]] 
Accuracy: 
 1.0


In [11]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    feed = {X: x_data, Y: y_data}
    for step in range(10001):
        sess.run(train, feed_dict=feed)
        if step % 200 ==0:
            print(step, sess.run(cost, feed_dict=feed))
            
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print("\nHypothesis: \n", h, "\nCorrect (Y): \n", c, "\nAccuracy: \n", a)

0 1.0619
200 0.759954
400 0.698564
600 0.673401
800 0.655318
1000 0.639872
1200 0.626188
1400 0.613966
1600 0.603018
1800 0.593189
2000 0.584344
2200 0.576365
2400 0.569148
2600 0.562605
2800 0.556656
3000 0.551235
3200 0.546282
3400 0.541744
3600 0.537579
3800 0.533746
4000 0.530211
4200 0.526944
4400 0.52392
4600 0.521114
4800 0.518506
5000 0.516078
5200 0.513815
5400 0.511701
5600 0.509724
5800 0.507873
6000 0.506138
6200 0.504508
6400 0.502977
6600 0.501536
6800 0.500178
7000 0.498899
7200 0.497691
7400 0.49655
7600 0.495472
7800 0.494452
8000 0.493486
8200 0.49257
8400 0.491702
8600 0.490879
8800 0.490097
9000 0.489354
9200 0.488648
9400 0.487976
9600 0.487336
9800 0.486728
10000 0.486147

Hypothesis: 
 [[ 0.41318852]
 [ 0.92761612]
 [ 0.30515379]
 [ 0.94083804]
 [ 0.10976764]
 [ 0.77413893]
 [ 0.93846077]
 [ 0.60639107]
 [ 0.313191  ]
 [ 0.47242877]
 [ 0.63977188]
 [ 0.18154544]
 [ 0.20091327]
 [ 0.39003286]
 [ 0.71860689]
 [ 0.35286897]
 [ 0.72381961]
 [ 0.82684427]
 [ 0.7957062