In [1]:
import tensorflow as tf

In [15]:
tf.set_random_seed(777)
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        

Tensor("add_32:0", dtype=float32)
0 Cost:  940.553 
Prediction:
 [ 132.19496155  147.32862854  150.86448669  167.0267334   107.31474304]
10 Cost:  43.5438 
Prediction:
 [ 158.66229248  179.1857605   182.23031616  201.18499756  131.62362671]
20 Cost:  43.3212 
Prediction:
 [ 158.7184906   179.29859924  182.31802368  201.28219604  131.71957397]
30 Cost:  43.108 
Prediction:
 [ 158.69487     179.31532288  182.31111145  201.27632141  131.74220276]
40 Cost:  42.8959 
Prediction:
 [ 158.6710968   179.33175659  182.30397034  201.27018738  131.76457214]
50 Cost:  42.685 
Prediction:
 [ 158.64736938  179.34814453  182.29681396  201.2640686   131.78686523]
60 Cost:  42.4751 
Prediction:
 [ 158.62368774  179.36444092  182.28968811  201.25793457  131.80911255]
70 Cost:  42.2664 
Prediction:
 [ 158.60006714  179.3807373   182.28256226  201.25183105  131.83126831]
80 Cost:  42.0588 
Prediction:
 [ 158.57653809  179.3969574   182.27549744  201.24572754  131.85340881]
90 Cost:  41.8522 
Prediction:
 [

840 Cost:  29.1374 
Prediction:
 [ 156.96498108  180.50909424  181.79107666  200.82254028  133.37428284]
850 Cost:  29.0001 
Prediction:
 [ 156.94595337  180.52224731  181.78535461  200.81747437  133.39231873]
860 Cost:  28.8635 
Prediction:
 [ 156.92697144  180.53533936  181.77964783  200.81239319  133.41030884]
870 Cost:  28.7276 
Prediction:
 [ 156.90805054  180.5484314   181.77398682  200.80734253  133.42825317]
880 Cost:  28.5924 
Prediction:
 [ 156.88917542  180.56144714  181.76831055  200.80230713  133.44616699]
890 Cost:  28.4579 
Prediction:
 [ 156.87036133  180.57444763  181.76266479  200.79727173  133.46401978]
900 Cost:  28.3241 
Prediction:
 [ 156.85159302  180.58743286  181.75704956  200.79225159  133.48184204]
910 Cost:  28.1911 
Prediction:
 [ 156.83285522  180.6003418   181.75143433  200.78723145  133.49960327]
920 Cost:  28.0588 
Prediction:
 [ 156.81420898  180.61323547  181.74584961  200.78225708  133.51731873]
930 Cost:  27.9272 
Prediction:
 [ 156.79559326  180.62

1650 Cost:  20.0812 
Prediction:
 [ 155.58230591  181.46464539  181.37718201  200.44714355  134.69241333]
1660 Cost:  19.992 
Prediction:
 [ 155.56710815  181.47517395  181.37265015  200.44291687  134.70700073]
1670 Cost:  19.9033 
Prediction:
 [ 155.55195618  181.485672    181.36811829  200.43870544  134.72154236]
1680 Cost:  19.8151 
Prediction:
 [ 155.53683472  181.49612427  181.36361694  200.43453979  134.73606873]
1690 Cost:  19.7274 
Prediction:
 [ 155.52174377  181.50654602  181.35910034  200.43032837  134.7505188 ]
1700 Cost:  19.6401 
Prediction:
 [ 155.50671387  181.51695251  181.35461426  200.42616272  134.76495361]
1710 Cost:  19.5533 
Prediction:
 [ 155.49172974  181.52734375  181.35015869  200.42202759  134.77935791]
1720 Cost:  19.4669 
Prediction:
 [ 155.47677612  181.53765869  181.34570312  200.41784668  134.79371643]
1730 Cost:  19.381 
Prediction:
 [ 155.46185303  181.54798889  181.3412323   200.41371155  134.80802917]
1740 Cost:  19.2956 
Prediction:
 [ 155.44700623

In [16]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

Tensor("add_35:0", dtype=float32)
0 Cost:  1711.44 
Prediction:
 [ 132.49588013  147.62954712  151.16540527  167.32765198  107.61566925]
10 Cost:  974.409 
Prediction:
 [ 156.47663879  176.50367737  179.58979797  198.27409363  129.65791321]
20 Cost:  973.87 
Prediction:
 [ 156.52284241  176.61006165  179.66893005  198.35328674  129.75761414]
30 Cost:  973.338 
Prediction:
 [ 156.49665833  176.62934875  179.66229248  198.33906555  129.79083252]
40 Cost:  972.809 
Prediction:
 [ 156.47039795  176.64834595  179.65545654  198.32460022  129.8237915 ]
50 Cost:  972.282 
Prediction:
 [ 156.44418335  176.6672821   179.64865112  198.31019592  129.85667419]
60 Cost:  971.756 
Prediction:
 [ 156.41809082  176.68615723  179.64187622  198.29577637  129.88949585]
70 Cost:  971.233 
Prediction:
 [ 156.39204407  176.70497131  179.63511658  198.28138733  129.92219543]
80 Cost:  970.711 
Prediction:
 [ 156.36608887  176.72372437  179.62838745  198.26699829  129.9548645 ]
90 Cost:  970.191 
Prediction:
 

940 Cost:  931.926 
Prediction:
 [ 154.41441345  178.14353943  179.13378906  197.10072327  132.5018158 ]
950 Cost:  931.535 
Prediction:
 [ 154.39472961  178.15797424  179.12895203  197.08792114  132.52864075]
960 Cost:  931.147 
Prediction:
 [ 154.37512207  178.17237854  179.12413025  197.07514954  132.5553894 ]
970 Cost:  930.759 
Prediction:
 [ 154.35554504  178.18670654  179.11932373  197.06236267  132.58206177]
980 Cost:  930.372 
Prediction:
 [ 154.33607483  178.20101929  179.11454773  197.04962158  132.60870361]
990 Cost:  929.987 
Prediction:
 [ 154.31663513  178.21528625  179.10978699  197.03688049  132.63528442]
1000 Cost:  929.603 
Prediction:
 [ 154.29725647  178.22947693  179.10502625  197.02412415  132.66177368]
1010 Cost:  929.22 
Prediction:
 [ 154.2779541   178.24363708  179.10028076  197.01142883  132.68821716]
1020 Cost:  928.838 
Prediction:
 [ 154.25872803  178.25778198  179.09559631  196.99873352  132.71463013]
1030 Cost:  928.457 
Prediction:
 [ 154.23956299  178

1830 Cost:  901.283 
Prediction:
 [ 152.89370728  179.26896667  178.77258301  196.020401    134.67138672]
1840 Cost:  900.979 
Prediction:
 [ 152.8790741   179.27993774  178.76927185  196.00891113  134.69348145]
1850 Cost:  900.676 
Prediction:
 [ 152.86448669  179.29084778  178.76594543  195.99740601  134.71549988]
1860 Cost:  900.374 
Prediction:
 [ 152.84994507  179.30172729  178.76266479  195.9859314   134.73748779]
1870 Cost:  900.072 
Prediction:
 [ 152.83546448  179.31259155  178.75939941  195.97447205  134.75942993]
1880 Cost:  899.771 
Prediction:
 [ 152.82102966  179.32341003  178.75611877  195.9630127   134.78132629]
1890 Cost:  899.472 
Prediction:
 [ 152.80664062  179.33421326  178.75289917  195.95158386  134.80316162]
1900 Cost:  899.172 
Prediction:
 [ 152.7922821   179.34495544  178.74964905  195.94013977  134.82496643]
1910 Cost:  898.873 
Prediction:
 [ 152.77799988  179.35568237  178.7464447   195.92874146  134.84672546]
1920 Cost:  898.576 
Prediction:
 [ 152.763717

1e-05