# Training and Test datasets

## small learning rate(1e-10)

In [1]:
import tensorflow as tf

In [4]:
tf.set_random_seed(777)
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=1e-10).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
1 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
2 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
3 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
4 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
5 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
6 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
7 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0

121 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
122 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
123 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
124 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
125 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
126 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
127 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
128 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]


194 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
195 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
196 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
197 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
198 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
199 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
200 6.20213 [[-0.82212889 -0.2921983   0.9995392 ]
 [ 1.22073805 -0.57642508 -1.41125774]
 [-0.65409166 -0.61371785 -1.53073502]]
Prediction: [0 2 0]
Accuracy:  0.333333


## big learning rate (1.5)

In [6]:
tf.set_random_seed(777)
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=1.5).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 4.10744 [[-1.30222011  1.34119952  0.0091089 ]
 [-2.26837182  2.60242152  1.24224782]
 [-1.71102452  2.79830837  0.74882114]]
1 19.6157 [[-0.92722011  0.40457785  0.57073057]
 [ 0.16912818 -1.3332932   2.7404623 ]
 [ 0.72647548 -0.95078254  2.06041241]]
2 20.9345 [[-0.5522275   0.96707761 -0.36676174]
 [ 2.60661316  1.29170609 -2.32202244]
 [ 3.16396785  1.86171699 -3.18957996]]
3 14.2091 [[-1.65749359  1.50984383  0.1957382 ]
 [-1.477355    3.87567449 -0.82202256]
 [-0.93907952  4.6522646  -1.87707996]]
4 29.6629 [[-1.28249359  0.57234383  0.7582382 ]
 [ 0.960145   -0.06182551  0.67797744]
 [ 1.49842048  0.9022646  -0.56457996]]
5 2.70875 [[-2.1213994   1.08563483  1.08385301]
 [-2.48576164  2.43954015  1.62251794]
 [-2.16142678  3.57455683  0.42297524]]
6 21.4102 [[-1.7463994   0.1596539   1.63483393]
 [-0.04826164 -1.47469449  3.0992527 ]
 [ 0.27607322 -0.16369581  1.72372794]]
7 22.7472 [[-1.3713994   0.7221539   0.69733405]
 [ 2.38923812  1.15030551 -1.9632473 ]
 [ 2.71357298  2

121 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
122 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
123 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
124 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
125 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
126 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
127 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
128 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
129 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
130 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
131 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
132 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
133 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
134 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
135 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan  nan]]
136 nan [[ nan  nan  nan]
 [ nan  nan  nan]
 [ nan  nan

## suitable learning rate (0.1)

In [7]:
tf.set_random_seed(777)
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(
    learning_rate=0.1).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 8.35157 [[-0.1952599  -0.21526977 -1.37132132]
 [ 0.58103514 -0.71268034  1.03534222]
 [ 1.442307   -0.27379474  0.76180577]]
1 5.92088 [[-0.26293892 -0.17831673 -1.34059536]
 [ 0.33468652 -0.53880268  1.10781324]
 [ 1.19022202 -0.08687477  0.8269707 ]]
2 4.43107 [[-0.28509218 -0.14258973 -1.35416913]
 [ 0.33232632 -0.36754179  0.93891257]
 [ 1.16293693  0.09856234  0.66881877]]
3 3.42136 [[-0.33150822 -0.1089743  -1.34136856]
 [ 0.19287613 -0.20108108  0.91190207]
 [ 1.00459945  0.28090659  0.64481205]]
4 2.48839 [[-0.35020867 -0.08142696 -1.35021544]
 [ 0.19198261 -0.04991347  0.76162797]
 [ 0.9783833   0.44958621  0.50234854]]
5 1.74744 [[-0.38227996 -0.06580876 -1.33376241]
 [ 0.09425901  0.06281688  0.74662125]
 [ 0.86484277  0.57797235  0.48750293]]
6 1.48368 [[-0.38271582 -0.07724877 -1.32188654]
 [ 0.14463106  0.06038029  0.69868577]
 [ 0.90660936  0.58233917  0.44136956]]
7 1.4471 [[-0.39531612 -0.08633231 -1.30020273]
 [ 0.1284782   0.06504714  0.71017176]
 [ 0.88298613  0.

104 0.782348 [[-1.07716429 -0.79025286  0.08556581]
 [ 0.35150033  0.13555129  0.41664556]
 [ 0.92691278  0.80117267  0.20223278]]
105 0.779461 [[-1.08274603 -0.79414958  0.09504423]
 [ 0.3526355   0.13697672  0.41408497]
 [ 0.92796785  0.80152035  0.20083006]]
106 0.776617 [[-1.08830428 -0.79799646  0.10444938]
 [ 0.35376018  0.13839157  0.41154546]
 [ 0.92902607  0.8018592   0.19943298]]
107 0.773816 [[-1.09383941 -0.80179411  0.11378212]
 [ 0.35487431  0.13979581  0.4090271 ]
 [ 0.93008733  0.80218977  0.1980412 ]]
108 0.771055 [[-1.09935153 -0.80554318  0.12304331]
 [ 0.35597801  0.14118923  0.40652999]
 [ 0.93115163  0.80251229  0.19665438]]
109 0.768335 [[-1.10484099 -0.80924428  0.1322338 ]
 [ 0.35707134  0.14257169  0.40405422]
 [ 0.93221897  0.80282712  0.19527219]]
110 0.765656 [[-1.11030793 -0.81289798  0.14135441]
 [ 0.35815439  0.14394312  0.40159976]
 [ 0.93328941  0.80313462  0.19389428]]
111 0.763015 [[-1.11575258 -0.8165049   0.150406  ]
 [ 0.35922709  0.14530341  0.39

197 0.624877 [[-1.52071226 -1.00299311  0.74185425]
 [ 0.41972956  0.22375423  0.2602134 ]
 [ 1.03588784  0.81829166  0.07613894]]
198 0.623882 [[-1.52486598 -1.00416732  0.74718219]
 [ 0.42014381  0.22432119  0.25923219]
 [ 1.03714144  0.81839734  0.07477961]]
199 0.622895 [[-1.52901006 -1.00532603  0.7524851 ]
 [ 0.4205533   0.22488269  0.25826123]
 [ 1.038396    0.81850165  0.07342077]]
200 0.621915 [[-1.53314459 -1.00646949  0.75776315]
 [ 0.42095786  0.22543894  0.25730041]
 [ 1.03965127  0.81860471  0.07206244]]
Prediction: [2 2 2]
Accuracy:  1.0


## Non-normalized inputs

In [8]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  2.7921e+12 
Prediction:
 [[-1177925.375]
 [-2371896.5  ]
 [-1865760.375]
 [-1307713.75 ]
 [-1541312.875]
 [-1554291.75 ]
 [-1424517.5  ]
 [-1813858.75 ]]
1 Cost:  3.06763e+27 
Prediction:
 [[  3.90690358e+13]
 [  7.86499780e+13]
 [  6.18710927e+13]
 [  4.33713054e+13]
 [  5.11154040e+13]
 [  5.15456306e+13]
 [  4.72433568e+13]
 [  6.01501823e+13]]
2 Cost:  inf 
Prediction:
 [[ -1.29499558e+21]
 [ -2.60695931e+21]
 [ -2.05080064e+21]
 [ -1.43760037e+21]
 [ -1.69428880e+21]
 [ -1.70854931e+21]
 [ -1.56594466e+21]
 [ -1.99375875e+21]]
3 Cost:  inf 
Prediction:
 [[  4.29243752e+28]
 [  8.64111747e+28]
 [  6.79765482e+28]
 [  4.76511996e+28]
 [  5.61594825e+28]
 [  5.66321678e+28]
 [  5.19053434e+28]
 [  6.60858166e+28]]
4 Cost:  inf 
Prediction:
 [[ -1.42278616e+36]
 [ -2.86421470e+36]
 [ -2.25317431e+36]
 [ -1.57946318e+36]
 [ -1.86148184e+36]
 [ -1.87714953e+36]
 [ -1.72047251e+36]
 [ -2.19050341e+36]]
5 Cost:  inf 
Prediction:
 [[ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]
 [ inf]
 [

## Normalized inputs (min-max scale)

In [10]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

xy = MinMaxScaler(xy)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  1.65831 
Prediction:
 [[ 3.59851742]
 [ 2.21108341]
 [ 1.76637876]
 [ 1.21805656]
 [ 1.71157539]
 [ 1.50633109]
 [ 0.24619541]
 [-0.33685863]]
1 Cost:  1.65821 
Prediction:
 [[ 3.59845567]
 [ 2.21102715]
 [ 1.76633239]
 [ 1.21802044]
 [ 1.71153212]
 [ 1.50628972]
 [ 0.24616954]
 [-0.33688283]]
2 Cost:  1.65811 
Prediction:
 [[ 3.59839344]
 [ 2.21097088]
 [ 1.76628518]
 [ 1.2179842 ]
 [ 1.71148896]
 [ 1.50624824]
 [ 0.24614364]
 [-0.33690709]]
3 Cost:  1.65801 
Prediction:
 [[ 3.59833193]
 [ 2.21091461]
 [ 1.76623857]
 [ 1.21794832]
 [ 1.71144569]
 [ 1.50620663]
 [ 0.24611774]
 [-0.33693132]]
4 Cost:  1.65791 
Prediction:
 [[ 3.59827018]
 [ 2.21085858]
 [ 1.7661922 ]
 [ 1.2179122 ]
 [ 1.71140265]
 [ 1.50616527]
 [ 0.24609184]
 [-0.33695555]]
5 Cost:  1.6578 
Prediction:
 [[ 3.59820843]
 [ 2.21080232]
 [ 1.76614511]
 [ 1.21787608]
 [ 1.71135938]
 [ 1.5061239 ]
 [ 0.24606594]
 [-0.33697981]]
6 Cost:  1.6577 
Prediction:
 [[ 3.59814692]
 [ 2.21074653]
 [ 1.7660985 ]
 [ 1.21784019]

93 Cost:  1.64886 
Prediction:
 [[ 3.59279156]
 [ 2.20587611]
 [ 1.76204324]
 [ 1.2147069 ]
 [ 1.70756888]
 [ 1.50248408]
 [ 0.24379192]
 [-0.33910891]]
94 Cost:  1.64876 
Prediction:
 [[ 3.59273005]
 [ 2.20582056]
 [ 1.76199675]
 [ 1.21467113]
 [ 1.70752597]
 [ 1.50244284]
 [ 0.24376613]
 [-0.33913305]]
95 Cost:  1.64866 
Prediction:
 [[ 3.59266853]
 [ 2.20576429]
 [ 1.76195037]
 [ 1.21463501]
 [ 1.70748293]
 [ 1.50240147]
 [ 0.24374036]
 [-0.33915719]]
96 Cost:  1.64856 
Prediction:
 [[ 3.59260726]
 [ 2.20570874]
 [ 1.76190352]
 [ 1.21459901]
 [ 1.7074399 ]
 [ 1.50236011]
 [ 0.24371454]
 [-0.33918133]]
97 Cost:  1.64846 
Prediction:
 [[ 3.59254575]
 [ 2.20565271]
 [ 1.76185703]
 [ 1.21456313]
 [ 1.70739698]
 [ 1.50231886]
 [ 0.24368872]
 [-0.33920547]]
98 Cost:  1.64836 
Prediction:
 [[ 3.592484  ]
 [ 2.20559692]
 [ 1.76181042]
 [ 1.21452713]
 [ 1.70735395]
 [ 1.50227749]
 [ 0.24366295]
 [-0.33922961]]
99 Cost:  1.64825 
Prediction:
 [[ 3.59242272]
 [ 2.20554066]
 [ 1.76176405]
 [ 1.