In [2]:
import tensorflow as tf
import numpy as np
import pprint as pp

sess = tf.InteractiveSession()

In [12]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


## 2d Array

In [13]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


## Matmul

In [24]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print(tf.matmul(matrix1, matrix2).eval())
print(tf.matmul(matrix1, matrix2))

[[ 12.]]
Tensor("MatMul_5:0", shape=(1, 1), dtype=float32)


## Reduce sum

In [6]:
x = [[1., 2.,],[3., 4.]]

tf.reduce_mean(x).eval()

2.5

In [8]:
tf.reduce_mean(x, axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [9]:
tf.reduce_mean(x, axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [10]:
tf.reduce_mean(x, axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

In [11]:
tf.reduce_sum(x).eval()

10.0

In [12]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [13]:
tf.reduce_sum(x, axis=1).eval()

array([ 3.,  7.], dtype=float32)

In [14]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [15]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

## Argmax
- 가장 큰값의 위치

In [16]:
x = [[0, 1, 2], [2, 1, 0]]

tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [17]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [18]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

## Reshape **

In [19]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

- 형태는 그대로 가져가면서 rank만 변경

In [21]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Reshape (squeeze, expand)

In [22]:
tf.squeeze([[0],[1],[2]]).eval()

array([0, 1, 2], dtype=int32)

In [23]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

## One hot

In [26]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

- rank가 하나 늘어난다.
- 이게 싫으면 reshape 해준다.

In [27]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

## Casting
- 텐서형변환

In [28]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [29]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

## Stack

In [31]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [32]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

## Ones and Zeros like
- 형태가 같은 단위행렬, 0행렬 생성

In [33]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [34]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

## Zip

In [35]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [36]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
