In [1]:
import tensorflow as tf

In [2]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

0 10.2702
200 0.956636
400 0.813461
600 0.720452
800 0.657639
1000 0.612007
1200 0.576883
1400 0.548746
1600 0.525511
1800 0.505845
2000 0.488856


In [7]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9],[1, 3, 4, 3],[1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

[[  5.38144959e-05   8.12927425e-01   1.87018767e-01]
 [  3.17779034e-01   6.72274604e-02   6.14993572e-01]
 [  2.40943074e-01   2.26783201e-01   5.32273710e-01]] [1 2 2]


In [8]:
import tensorflow as tf
import numpy as np

In [21]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

nb_classes = 7

X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])

Y_one_hot = tf.one_hot(Y, nb_classes)
print('one_hot', Y_one_hot)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print('reshape', Y_one_hot)

W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=Y_one_hot)

cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={X: x_data, Y: y_data})
            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2f}".format(step, loss, acc))
            
    pred = sess.run(prediction, feed_dict={X: x_data})
    
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))
        


(101, 16) (101, 1)
one_hot Tensor("one_hot_11:0", shape=(?, 1, 7), dtype=float32)
reshape Tensor("Reshape_19:0", shape=(?, 7), dtype=float32)
Step:     0	Loss: 4.897	Acc: 0.26
Step:   100	Loss: 0.816	Acc: 0.82
Step:   200	Loss: 0.538	Acc: 0.87
Step:   300	Loss: 0.398	Acc: 0.91
Step:   400	Loss: 0.314	Acc: 0.92
Step:   500	Loss: 0.257	Acc: 0.94
Step:   600	Loss: 0.217	Acc: 0.94
Step:   700	Loss: 0.187	Acc: 0.94
Step:   800	Loss: 0.164	Acc: 0.95
Step:   900	Loss: 0.145	Acc: 0.97
Step:  1000	Loss: 0.130	Acc: 0.98
Step:  1100	Loss: 0.118	Acc: 0.99
Step:  1200	Loss: 0.108	Acc: 1.00
Step:  1300	Loss: 0.099	Acc: 1.00
Step:  1400	Loss: 0.091	Acc: 1.00
Step:  1500	Loss: 0.085	Acc: 1.00
Step:  1600	Loss: 0.079	Acc: 1.00
Step:  1700	Loss: 0.074	Acc: 1.00
Step:  1800	Loss: 0.070	Acc: 1.00
Step:  1900	Loss: 0.066	Acc: 1.00
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 Tr